"""Reusable document export helpers.

The Streamlit frontend currently contains the download implementation so
that generated bytes can be sent directly to the browser. These helpers are
kept here for future backend/export refactoring.
"""

from io import BytesIO
from docx import Document


def create_docx(text: str) -> bytes:
    document = Document()
    for paragraph in text.split("\n"):
        document.add_paragraph(paragraph)

    output = BytesIO()
    document.save(output)
    return output.getvalue()
